news/api/urls.py
from django.urls import include, path

app_name = 'api'  # pylint: disable=invalid-name

urlpatterns = [
]

news/urls.py
from django.urls import include, path
from .views import IndexView

app_name = 'news'  # pylint: disable=invalid-name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('api/', include('news.api.urls')),
]

root/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import IndexView, LoggedOutView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'root'  # pylint: disable=invalid-name

urlpatterns = [
    path('', IndexView.as_view(), name='root_index'),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
    path('accounts/logged-out/', LoggedOutView.as_view(), name="logged-out"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

alerts/models.py
from django.db import models
from root.utils.func.get_apps import get_apps
# Create your models here.


class Notification(models.Model):
    """
    Model to hold global announcements
    """
    # Bootstrap CSS Class that will be passed to the template.
    COLOR_CHOICES = [('primary', 'primary '), ('success', 'success'),
                     ('warning', 'warning'), ('danger', 'danger')]

    admin_panel_name = models.CharField(
        max_length=100, blank=False, null=False, verbose_name="Name")
    display = models.BooleanField(default=False)
    expiration_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField(auto_created=True)
    color = models.CharField(max_length=15, choices=COLOR_CHOICES)
    title = models.CharField(max_length=100, blank=True, null=True)
    # replace this with a WYSIWYG later
    body = models.TextField(blank=False, null=False)
    app = models.CharField(max_length=30, null=True, blank=True, choices=get_apps(
    ), help_text="Which app to show announcement on. None will show on all.")

    def __str__(self):
        return f'{self.admin_panel_name} ({self.color.upper()}) {f"({self.app})" if self.app else ""}'

    class Meta:
        verbose_name = "Annoucement"

news/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User


# Create your models here.


class NewsArticle(models.Model):
    """News Article Model"""
    title = models.CharField(max_length=50, blank=False, null=False)
    short_description = models.TextField(blank=True, null=True)
    content = RichTextField()
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    spotlight = models.BooleanField(default=False)
    spotlight_expiry = models.DateTimeField(null=True, blank=True)
    create_dttm = models.DateTimeField(auto_now_add=True, editable=False)
    updated_dttm = models.DateTimeField(auto_now=True, editable=False)

alerts/views.py
from django.shortcuts import render

# Create your views here.

news/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView
from .models import NewsArticle
# Create your views here.


class IndexView(TemplateView):
    def get(self, request, *args, **kwargs):
        articles = NewsArticle.objects.all()
        context = {
            'articles': articles
        }
        return render(request, "news/index.html", context=context)

root/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.urls import reverse

# Generic Homepage like views that do no belong to an app.


class IndexView(TemplateView):
    def get(self, request, *args, **kwargs):
        context = {'app_name': reverse('root_index')}
        return render(request, "home/index.html", context=context)


class LoggedOutView(TemplateView):
    def get(self, request, *args, **kwargs):
        return render(request, "registration/logged-out.html", context={})

templates/alerts/notification.html
{% block notification %}
    {% spaceless %}
        <div class="alert alert-{{ notification.color }} my-3" role="alert">
            {% if notification.title %}
                <h5 class="alert-heading">{{ notification.title }}</h5>
                <hr>
            {% endif %}
            {{ notification.body|safe }}
        </div>
    {% endspaceless %}
{% endblock notification %}

templates/alerts/notifiication_v2.html
{% block notification %}
    {% spaceless %}
        <div class="toast fade show" id="notification_{{ notification.id }}">
            <div class="toast-header">
                <strong class="me-auto"><i class="alert-circle"></i> {{ notification.title }}</strong>
                <small>{{ notification.create_date|timesince }} ago</small>
                <button type="button"
                        class="btn-close"
                        data-bs-dismiss="toast"
                        aria-label="Close"></button>
            </div>
            <div class="toast-body">{{ notification.body|safe }}</div>
        </div>
    {% endspaceless %}
{% endblock notification %}

templates/home/index.html
{% load static %}
{% load cache %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>
      {% block title %}
        SeZiMo Gaming
      {% endblock title %}
    </title>
    {# Bootstrap CSS #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
          crossorigin="anonymous"/>
    {# Feather Icons #}
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
  </head>
  <body style="background-color: #ededed">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    {% include "home/navbar.html" %}
    <div class="container">
      <div class="col-sm-1"></div>
      <div class="col-sm">
        <div class="container">
          <div class="row">
            <div class="col"></div>
            <div class="col-10">
              {% cache 1 notification_cache app_announcement_cache %}
              {% if notifications %}
                {% for notification in notifications %}
                  {% include "alerts/notification.html" with notification=notification %}
                {% endfor %}
              {% endif %}
            {% endcache notification_cache %}
            {% block content %}
            {% endblock content %}
          </div>
          <div class="col"></div>
        </div>
      </div>
    </div>
  </div>
</body>
<script>feather.replace({'stroke-width': 2  });</script>
</html>

templates/home/navbar.html
{% load static %}
<link rel='stylesheet' href="{% static 'css/style.css' %}" type='text/css'>
<nav class="navbar navbar-expand-lg navbar-dark"
     style="background-color: #392de3">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'root_index' %}">SeZiMo</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item pr-2">
                    <a class="nav-link {% if request.resolver_match.url_name == 'root_index' %} active{% endif %}"
                       href="{% url 'root_index' %}"><i data-feather="home"></i> Home</a>
                </li>
                <li class="nav-item pr-1">
                    <a class="nav-link {% if request.resolver_match.app_name == 'news' %} active{% endif %}"
                       href="{% url 'news:index' %}"><i data-feather="book-open"></i> News</a>
                </li>
                <li class="nav-item pr-1">
                    <a class="nav-link disabled"><i data-feather="mail"></i> Contact Us <small>(Coming Soon)</small></a>
                </li>
            </ul>
        </div>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                   href="#"
                   id="navbarDropdown"
                   role="button"
                   data-bs-toggle="dropdown"
                   aria-expanded="false">
                    {{ request.user }}
                </a>
                <ul class="dropdown-menu dropdown-menu-end"
                    aria-labelledby="navbarDropdown">
                    {% if request.user.is_authenticated %}
                        {% include "home/navbar_auth_dropdown.html" %}
                    {% else %}
                        <li>
                            <a class="dropdown-item" href="{% url 'auth:login' %}"><i data-feather="log-in"></i> Login</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#"><i data-feather="user-plus"></i> Create Account</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#"><i data-feather="lock"></i> Forgot Password?</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#"><i data-feather="code"></i> Swagger Docs</a>
                        </li>
                    {% endif %}
                </ul>
            </li>
        </ul>
    </div>
</nav>

templates/home/navbar_auth_dropdown.html
<li>
    <a class="dropdown-item" href="#"><i data-feather="settings"></i> Edit Account</a>
</li>
<li>
    <a class="dropdown-item" href="#"><i data-feather="code"></i> Swagger Docs</a>
</li>
{% if request.user.is_staff %}
    <li>
        <hr class="dropdown-divider">
    </li>
    <li>
        <a class="dropdown-item" href="#"><i data-feather="tool"></i> Django Admin</a>
    </li>
    <li>
        <hr class="dropdown-divider">
    </li>
{% endif %}
<li>
    <a class="dropdown-item" href="{% url 'auth:logout' %}"><i data-feather="log-out"></i> Logout</a>
</li>

templates/news/carousel.html
<div id="carouselExampleCaptions"
     class="carousel slide"
     data-bs-ride="false">
    <div class="carousel-indicators">
        <button type="button"
                data-bs-target="#carouselExampleCaptions"
                data-bs-slide-to="0"
                class="active"
                aria-current="true"
                aria-label="Slide 1">
        </button>
        <button type="button"
                data-bs-target="#carouselExampleCaptions"
                data-bs-slide-to="1"
                aria-label="Slide 2"></button>
        <button type="button"
                data-bs-target="#carouselExampleCaptions"
                data-bs-slide-to="2"
                aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKz_z-MDBzkYGYwKtKVksyv-pMe_XIvfMgMQ&usqp=CAU"
                 class="d-block w-100"
                 alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>First slide label</h5>
                <p>Some representative placeholder content for the first slide.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOCVjGm_GXQSH3jRwwfMGc9sollIvlg_mFMg&usqp=CAU"
                 class="d-block w-100"
                 alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Second slide label</h5>
                <p>Some representative placeholder content for the second slide.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxYWYD_R-9-mJr5gQpbAS8aY-zft6E3H5kCw&usqp=CAU"
                 class="d-block w-100"
                 alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Third slide label</h5>
                <p>Some representative placeholder content for the third slide.</p>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev"
            type="button"
            data-bs-target="#carouselExampleCaptions"
            data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next"
            type="button"
            data-bs-target="#carouselExampleCaptions"
            data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

templates/news/index.html
{% extends "home/index.html" %}
{% block content %}
    <h1>Welcome to the news page!</h1>
    <!-- Dropdown Trigger -->
    <ul>
        {% for article in articles %}
            <li>{{ article.title }}</li>
            <ul>
                <li>Short Description: {{ article.short_description }}</li>
                <li>Content: {{ article.content|safe }}</li>
                <li>Author: {{ article.author.get_full_name }}</li>
                <li>Created: {{ article.create_dttm }}</li>
                <li>Modified: {{ article.updated_dttm }}</li>
            </ul>
        {% endfor %}
    </ul>
{% endblock content %}